image: archlinux
packages:
  - go
  - yarn
  - python-pip
sources:
  - https://github.com/MestreLion/git-tools
  - https://git.sr.ht/~idmyn/zettelkasten
  - https://git.sr.ht/~idmyn/notes
secrets:
  - c8bc7885-4bc0-4985-aea4-969b04fc99c1
tasks:
  - setup: |
      git-tools/git-restore-mtime --work-tree notes --git-dir notes/.git
      pip install fonttools brotli zopfli
      yarn add netlify-cli subfont
  - build: |
      export PATH=$PATH:/home/build/.local/bin
      cd zettelkasten
      NOTES_DIR="../notes" make
      yarn run subfont -i --root /home/build/zettelkasten/dist
  - deploy: |
      source .env &>/dev/null
      yarn run netlify deploy --prod --dir=zettelkasten/dist
